apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test-namespace
  labels:
    app: nginx
    environment: production
  annotations:
    description: "Nginx web server for production environment"
    owner: "platform team"
    version: "1.0.0"
spec:
  volumes:
  - name:  nginx-config-map-volume
    configMap:
      name: nginx-config-map
      items:
      - key: nginx.conf
        path: nginx.conf
  containers:
  - name: nginx-app
    image: nginx:1.27.4
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "200Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "512m"
    volumeMounts:
      - name:  nginx-config-map-volume
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-2 # 이미 있어서 -2 붙임
  namespace: test-namespace
  annotations:
    service.kubernetes.io/description: "Nginx NodePort service"
    prometheus.io/scrape: "tclerue"
    prometheus.io/port: "80"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports: 
  - protocol: TCP
    port: 3001
    targetPort: 80
    # nodePort: 30001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
  namespace: test-namespace
  annotations:
    config-version: "v1"
    last-modified: "2025-03-06"
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    
    events {
        worker_connections  1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        
        access_log  /var/log/nginx/access.log  main;
        
        sendfile        on;
        #tcp_nopush     on;
        
        keepalive_timeout  65;
        
        #gzip  on;
        
        server_tokens off;  # nginx 버전 정보 숨김
        
        include /etc/nginx/conf.d/*.conf;
    }