apiVersion: apps/v1
kind: Deployment
metadata:
  name:  fastapi-app
  namespace: application
  labels:
    app:  app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app:  app
  template:
    metadata:
      labels:
        app:  app
    spec:
      containers:
      - name:  fastapi-app-container
        image:  girr311/fastapi-app:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: fastapi-app-secret
        # env:
        # - name: REDIS_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: fastapi-app-secret
        #       key: REDIS_HOST
        #       optional: false
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "200Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name:  fastapi-app-service
  namespace: application
  annotations:
    service.kubernetes.io/description: "FastAPI Cluster IP service"
spec:
  selector:
    app:  app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000