apiVersion: v1
kind: Secret
metadata:
  name: fastapi-app-secret
  namespace: application
type: Opaque
data:
  REDIS_HOST: cmVkaXMtc3RhdGVmdWxzZXQtMC5yZWRpcy1zZXJ2aWNlLnJlZGlzLW5hbWVzcGFjZS5zdmMuY2x1c3Rlci5sb2NhbA==