spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: health, metrics, prometheus
      base-path: /
      path-mapping:
        health: /liveness
