apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-namespace
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name:  nginx-config-map-volume
          configMap:
            name: nginx-config-map
        
      containers:
      - name: nginx-container
        image: nginx:1.27.4
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
          name: nginx-port
        volumeMounts:
          - name:  nginx-config-map-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: fake.conf