apiVersion: v1
kind: Service
metadata:
  namespace: nginx-namespace
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 80  
      nodePort: 30004
  type: NodePort