apiVersion: v1
kind: Service
metadata:
  namespace: demo-nginx
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 3555
      targetPort: 80
  type: LoadBalancer