### GET Health
GET http://localhost:8080/liveness

### GET Health
GET http://localhost:8080/readiness

### GET Metrics
GET http://localhost:8080/metrics

### GET Prometheus
GET http://localhost:8080/prometheus

### GET factorial
GET http://localhost:8080/factorial

### GET cache
GET http://localhost:8080/cache