adminUser: "admin"  
adminPassword: "admin" 

# plugins: 
#   - redis-datasource

# dashboardProviders:
#   dashboardproviders.yaml:
#     apiVersion: 1
#     providers:
#       - name: 'Redis dashboard'
#         orgId: 11835
#         folder: ''
#         type: file
#         disableDeletion: false
#         editable: true
#         options:
#           path: /var/lib/grafana/dashboards/default