server:
  global:
    scrape_interval: 15s

  scrape_configs:
    - job_name: "redis-exporter-0"
      static_configs:
        - targets: ["redis-exporter-prometheus-redis-exporter.prometheus-namespace.svc:9121"]
