# https://artifacthub.io/packages/helm/prometheus-community/prometheus
grafana:
  enabled: false

server:
  global:
    scrape_interval: 15s
  
extraScrapeConfigs: |
  - job_name: "redis-exporter-0"
    static_configs:
      - targets: ["redis-exporter-prometheus-redis-exporter.monitoring.svc:9121"]
