apiVersion: apps/v1
kind: Deployment
metadata:
  name:  springboot-app
  namespace: application
  labels:
    app: my-springboot-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=girr311/springboot-app
    argocd-image-updater.argoproj.io/nginx.update-strategy: newest-build
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: my-springboot-app
  template:
    metadata:
      labels:
        app: my-springboot-app
    spec:
      containers:
      - name: springboot-app-container
        image: girr311/springboot-app:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: springboot-app-secret
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "500m" # 100이면 아예 안 올라옴
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
