apiVersion: v1
kind: Service
metadata:
  name:  springboot-app-service
  namespace: application
  annotations:
    service.kubernetes.io/description: "SpringBoot Cluster IP service"
spec:
  selector:
    app: my-springboot-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    