apiVersion: v1
kind: Service
metadata:
  name:  fastapi-app-service
  namespace: application
  annotations:
    service.kubernetes.io/description: "FastAPI Cluster IP service"
spec:
  selector:
    app:  app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000