apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-namespace
spec:
  clusterIP: None # Headless Service를 생성
  selector:
    app: storage
  ports:
  - name: redis
    port: 6379
    targetPort: 6379