apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  redis-statefulset
  namespace: redis-namespace
  labels:
    app: storage
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: storage  
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: redis-container
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "150m"      
